package vazkii.tinkerer.lib;

public final class LibItemIDs {

	public static final int DEFAULT_WAND_TINKERER = 21150;
	public static final int DEFAULT_GLOWSTONE_GAS = 21151;
	public static final int DEFAULT_SPELL_CLOTH = 21152;
	public static final int DEFAULT_STOPWATCH = 21153;
	public static final int DEFAULT_WAND_DISLOCATION = 21154;
	public static final int DEFAULT_NAMETAG = 21155;
	public static final int DEFAULT_XP_TALISMAN = 21156;
	public static final int DEFAULT_FIRE_BRACELET = 21157;
	public static final int DEFAULT_DARK_QUARTZ = 21158;
	public static final int DEFAULT_TELEPORT_SIGIL = 21159;
	public static final int DEFAULT_WAND_UPRISING = 21160;
	public static final int DEFAULT_SWORD_CONDOR = 21161;
	public static final int DEFAULT_DEATH_RUNE = 21162;
	public static final int DEFAULT_SILK_SWORD = 21163;
	public static final int DEFAULT_FORTUNE_MAUL = 21164;
	public static final int DEFAULT_ENDER_MIRROR = 21165;
	public static final int DEFAULT_GOLIATH_LEGS = 21166;
	public static final int DEFAULT_DARK_GAS = 21167;
	public static final int DEFAULT_GAS_REMOVER = 21168;
	public static final int DEFAULT_FLUX_DETECTOR = 21169;
	public static final int DEFAULT_CLEANSING_TALISMAN = 21170;
	public static final int DEFAULT_DUMMY_ENCHANTBOOK = 21171;
	public static final int DEFAULT_RESEARCH_SHARE_BOOK = 21172;
	public static final int DEFAULT_BRIGHT_NITOR = 21173;
	public static final int DEFAULT_RUNE = 21174;
	public static final int DEFAULT_SCYTHE = 21175;
	public static final int DEFAULT_RAINWATER_BOTTLE = 21176;
	public static final int DEFAULT_WEATHER_CRYSTAL = 21177;
	public static final int DEFAULT_LOVE_POTION = 21178;
	public static final int DEFAULT_SOUL_MOULD = 21179;
	public static final int DEFAULT_CONNECTOR = 21180;
	public static final int DEFAULT_ICE_GLOBE = 21181;
	public static final int DEFAULT_MURAMASA = 21182;

	public static int idWandTinkerer;
	public static int idGlowstoneGas;
	public static int idSpellCloth;
	public static int idStopwatch;
	public static int idWandDislocation;
	public static int idNametag;
	public static int idXpTalisman;
	public static int idFireBracelet;
	public static int idDarkQuartz;
	public static int idTeleportSigil;
	public static int idWandUprising;
	public static int idSwordCondor;
	public static int idDeathRune;
	public static int idSilkSword;
	public static int idFortuneMaul;
	public static int idEnderMirror;
	public static int idGoliathLegs;
	public static int idDarkGas;
	public static int idGasRemover;
	public static int idFluxDetector;
	public static int idCleansingTalisman;
	public static int idDummyEnchantbook;
	public static int idResearchShareBook;
	public static int idBrightNitor;
	public static int idRune;
	public static int idScythe;
	public static int idRainwaterBottle;
	public static int idWeatherCrystal;
	public static int idLovePotion;
	public static int idSoulMould;
	public static int idConnector;
	public static int idIceGlobe;
	public static int idMuramasa;

}
